//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionXml
    {
        public int Xml_Id { get; set; }
        public int Xml_TypeId { get; set; }
        public string XmlFile { get; set; }
    }
}
